export const typeComponent = {
    CHECKBOX: 'CHECKBOX',
    FONT_COLOR: 'FONT_COLOR',
    SELECT_SINGLE: 'SELECT_SINGLE',
    FILL_COLOR: 'FILL_COLOR',
    OPACITY: 'OPACITY',
    BORDER_COLOR: 'BORDER_COLOR',
    BORDER_RADIUS: 'BORDER_RADIUS',
    BORDER_WEIGHT: 'LINE_WEIGHT',
    LINE_STYLE: 'LINE_STYLE',
    FONT_FAMILY: 'FONT_FAMILY',
    FONT_SIZE: 'FONT_SIZE',
    TEXT_INPUT: 'TEXT_INPUT',
    SWITCH: 'SWITCH',
    ALIGNMENT: 'ALIGNMENT',
    LABEL: 'LABEL',
    COMPONENT_CHILD: 'COMPONENT_CHILD'
};

export const typeElement = {
    TEXT: 'TEXT',
    BUTTON: 'BUTTON',
    COLUMNS: 'COLUMNS',
    LINE: 'LINE',
    GENERAL: 'GENERAL'
};