const configs = {
    DATA_TYPE_TEXT: 1,
    DATA_TYPE_NUMBER: 2,
    DATA_TYPE_PERCENT: 3,
    DATA_TYPE_CURRENCY: 4,
    DATA_TYPE_DATE: 5,
    MAX_CHART_TICK_LINE: 100,
    ARRAY_TYPE_HAS_SUB_MENU: ['CURRENCY', 'DATE', 'COUNTRY', 'CITY', 'GEO'],
    CURRENCY: {
        CURRENCY_AED: 'dh',
        CURRENCY_ALL: 'Lek',
        CURRENCY_ARS: '$',
        CURRENCY_AUD: '$',
        CURRENCY_BDT: '৳',
        CURRENCY_BGN: 'lev',
        CURRENCY_BOB: 'Bs',
        CURRENCY_BRL: 'R$',
        CURRENCY_CAD: '$',
        CURRENCY_CDF: 'FrCD',
        CURRENCY_CHF: 'CHF',
        CURRENCY_CLP: '$',
        CURRENCY_CNY: '¥',
        CURRENCY_COP: '$',
        CURRENCY_CRC: '₡',
        CURRENCY_CZK: 'Kč',
        CURRENCY_DKK: 'kr.',
        CURRENCY_DOP: 'RD$',
        CURRENCY_EGP: '£',
        CURRENCY_ETB: 'Birr',
        CURRENCY_EUR: '€',
        CURRENCY_GBP: '£',
        CURRENCY_HKD: '$',
        CURRENCY_HRK: 'kn',
        CURRENCY_HUF: 'Ft',
        CURRENCY_IDR: 'Rp',
        CURRENCY_ILS: '₪',
        CURRENCY_INR: '₹',
        CURRENCY_IRR: 'Rial',
        CURRENCY_ISK: 'kr',
        CURRENCY_JMD: '$',
        CURRENCY_JPY: '¥',
        CURRENCY_KRW: '₩',
        CURRENCY_LKR: 'Rs',
        CURRENCY_LTL: 'Lt',
        CURRENCY_MNT: '₮',
        CURRENCY_MVR: 'Rf',
        CURRENCY_MXN: '$',
        CURRENCY_MYR: 'RM',
        CURRENCY_NOK: 'kr',
        CURRENCY_NZD: '$',
        CURRENCY_PAB: 'B/.',
        CURRENCY_PEN: 'S/.',
        CURRENCY_PHP: '₱',
        CURRENCY_PKR: 'Rs',
        CURRENCY_PLN: 'zł',
        CURRENCY_RON: 'RON',
        CURRENCY_RSD: 'din',
        CURRENCY_RUB: '₽',
        CURRENCY_SAR: 'Rial',
        CURRENCY_SEK: 'kr',
        CURRENCY_SGD: '$',
        CURRENCY_THB: '฿',
        CURRENCY_TRY: '₺',
        CURRENCY_TWD: 'NT$',
        CURRENCY_TZS: 'TSh',
        CURRENCY_UAH: 'грн.',
        CURRENCY_USD: '$',
        CURRENCY_UYU: '$U',
        CURRENCY_VEF: 'Bs',
        CURRENCY_VND: '₫',
        CURRENCY_YER: 'Yer',
        CURRENCY_ZAR: 'R'
    },
    LOCAL_STORAGE_PREFIX: '@antscorp/charts',
    DATA_TYPES: {
        1: 'Text (ABC)',
        2: 'Number (123)',
        3: 'Percent (%)',
        4: 'Currency (đ)',
        5: 'Date (YYYYMMDD)'
    },
    TYPE_TIME_RANGE: [
        'YEAR',
        'YEAR_QUARTER',
        'YEAR_MONTH',
        'WEEK',
        'DATE',
        'DATE_HOUR',
        'QUARTER',
        'MONTH',
        'DAY_OF_WEEK',
        'MONTH_DAY',
        'DAY_OF_MONTH',
        'HOUR',
        'MINUTE'
    ]
};

export default configs;