export const DATA_TYPE = {
    ACTION_TYPE: 'actionType',
    URL: 'url',
    TARGET: 'target',
    ACTION: 'action',
    RESPONSIVE_DESIGN: 'responsiveDesign',
    BACKGROUND_COLOR_BUTTON: 'backgroundColorButton',
    TEXT_COLOR_BUTTON: 'textColorButton',
    WIDTH: 'width',
    BUTTON: 'button',
    AUTO_WIDTH: 'autoWidth',
    ALIGNMENT: 'alignments',
    LINE_HEIGHT: 'lineHeight',
    BUTTON_PADDING: 'buttonPadding',
    MORE_OPTIONS_BUTTON_PADDING: 'moreOptionsButtonPadding',
    ROUNDED_BORDER: 'roundedBorder',
    BORDER: 'border',
    MORE_OPTIONS_BORDER: 'moreOptionsBorder',
    CHILD_BORDER: 'childBorder',
    CONTAINER_PADDING: 'containerPadding',
    MORE_OPTIONS_PADDING_BUTTON: 'moreOptionsPaddingButton',
    RESPONSIVE: 'responsive',
    UPLOAD_IMAGE: 'uploadImage',
    SELECT_RADIO: 'selectRadioImage',
    IMAGE_UPLOAD: 'imageUpload',
    ALTERNAL_TEXT: 'alternalText',
    IMAGE: 'image',
    CONTAINER_PADDING_IMAGE_LABEL: 'containerPaddingImageLabel',
    IMAGE_MORE_OPTION: 'imageMoreOptions',
    CHILD_IMAGE_PADDING: 'childImagePadding',
    CHILD_BUTTON_PADDING: 'childButtonPadding',

};

DATA_TYPE.BORDER