export const actionType = {
    INITIAL_DATA: 'INITIAL_DATA',
    UPDATE_BODY: 'UPDATE_BODY',
    UPDATE_ROW: 'UPDATE_ROW',
    UPDATE_COLUMN: 'UPDATE_COLUMN',
    UPDATE_CONTENT: 'UPDATE_CONTENT',
    UPDATE_MODE: 'UPDATE_MODE',
    ACTIVE_ELEMENT: 'ACTIVE_ELEMENT',
    DRAGGING_COLUMN_ID: 'DRAGGING_COLUMN_ID',
    HANDLE_ROW: 'HANDLE_ROW',
    DRAG_IT_HERE_SPECS: 'DRAG_IT_HERE_SPECS',
    RENDER_DRAG_POSITION: 'RENDER_DRAG_POSITION',
    UPDATE_DRAGGING_STATUS: 'UPDATE_DRAGGING_STATUS'
};