export const actionType = {
    INITIAL_DATA: 'INITIAL_DATA',
    UPDATE_BODY: 'UPDATE_BODY',
    UPDATE_ROW: 'UPDATE_ROW',
    UPDATE_COLUMN: 'UPDATE_COLUMN',
    UPDATE_CONTENT: 'UPDATE_CONTENT',
    UPDATE_MODE: 'UPDATE_MODE',
    ACTIVE_ELEMENT: 'ACTIVE_ELEMENT',
    HANDLE_ROW: 'HANDLE_ROW',
    HANDLE_CONTENT: 'HANDLE_CONTENT',
    TOGGLE_DELETE_FORM: 'TOGGLE_DELETE_FORM',
    CONFIRM_DELETE: 'CONFIRM_DELETE'
};