export const actionType = {
    INITIAL_DATA: 'INITIAL_DATA',
    UPDATE_BODY: 'UPDATE_BODY',
    UPDATE_ROW: 'UPDATE_ROW',
    UPDATE_COLUMN: 'UPDATE_COLUMN',
    UPDATE_CONTENT: 'UPDATE_CONTENT',
    UPDATE_MODE: 'UPDATE_MODE',
    ACTIVE_ELEMENT: 'ACTIVE_ELEMENT',
    DRAGGING_COLUMN_ID: 'DRAGGING_COLUMN_ID',
    ADD_ROWS: 'ADD_ROWS',
    DELETE_ROWS: 'DELETE_ROWS',
    DUPLICATE_ROW: 'DUPLICATE_ROW',
    HANDLE_ROW: 'HANDLE_ROW'
};